# Custom patterns for secret scanning
# These patterns supplement GitHub's built-in secret scanning

patterns:
  # Azure DevOps Personal Access Token
  - name: Azure DevOps PAT
    pattern: '\b[a-z0-9]{52}\b'
    description: Potential Azure DevOps Personal Access Token
    
  # Generic API Key patterns
  - name: Generic API Key
    pattern: '(?i)(api[_-]?key|apikey)\s*[:=]\s*["\']?([a-zA-Z0-9_\-]{32,})["\']?'
    description: Generic API key pattern
    
  # Connection strings with passwords
  - name: Connection String with Password
    pattern: '(?i)(password|pwd)\s*=\s*[^;"\s]+'
    description: Connection string containing password
    
  # Private keys
  - name: Private Key Block
    pattern: '-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----'
    description: Private cryptographic key
    
  # JWT tokens
  - name: JWT Token
    pattern: 'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}'
    description: JSON Web Token

# Paths to exclude from scanning
paths-ignore:
  - '**/*.md'
  - '**/docs/**'
  - '**/samples/**'
  - '**/*.json'
  - '**/*.xml'
  - '**/*.csproj'